name: make playlist templete
on:
  workflow_dispatch:

jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node 📋
        uses: actions/setup-node@v1
        with:
          node-version: "20.10.x"

      - name: Install m3u-linter 📋
        run: |
          npm install -g m3u-linter || true
#         m3u-linter -c ./m3u-linter.config.json ./work/playlist.m3u8

      - name: Install iptv-checker 📋
        run: |
          npm install -g iptv-checker || true
          sudo apt-get install -y ffmpeg

      # local
      - name: 1-0. Checkout local repo 🐾
        uses: actions/checkout@v4
        with:
          ref: main
          path: local

      # remote 1
      - name: 1-1. Checkout remote repo@iptv-org/iptv 🚀
        uses: actions/checkout@v4
        with:
          repository: iptv-org/iptv
          ref: gh-pages
          path: remote1
      - name: 1-2. Copy files 🚚
        run: |
          cd ${GITHUB_WORKSPACE}/local/work/
          rm -rf *
          cp -rfp ${GITHUB_WORKSPACE}/remote1/*  ${GITHUB_WORKSPACE}/local/work/
          tree -a
      - name: 1-3. Check files 🔥
        run: |
          cp -pr ${GITHUB_WORKSPACE}/local/work/index.category.m3u ${GITHUB_WORKSPACE}/local/docs/m3u/index.category.m3u
          cp -pr ${GITHUB_WORKSPACE}/local/work/index.country.m3u  ${GITHUB_WORKSPACE}/local/docs/m3u/index.country.m3u
          cp -pr ${GITHUB_WORKSPACE}/local/work/index.language.m3u ${GITHUB_WORKSPACE}/local/docs/m3u/index.language.m3u
          cp -pr ${GITHUB_WORKSPACE}/local/work/index.m3u          ${GITHUB_WORKSPACE}/local/docs/m3u/index.m3u


          if [ ! -d ${GITHUB_WORKSPACE}/local/docs/m3u/countries ]; then
            mkdir -p ${GITHUB_WORKSPACE}/local/docs/m3u/countries
          fi
          iptv-checker -o ${GITHUB_WORKSPACE}/local/output -p 100 -t 60000 ${GITHUB_WORKSPACE}/local/work/countries/jp.m3u
          cp -pr ${GITHUB_WORKSPACE}/local/output/online.m3u ${GITHUB_WORKSPACE}/local/docs/m3u/countries/jp.m3u
          
          iptv-checker -o ${GITHUB_WORKSPACE}/local/output -p 100 -t 60000 ${GITHUB_WORKSPACE}/local/work/countries/cn.m3u
          cp -pr ${GITHUB_WORKSPACE}/local/output/online.m3u ${GITHUB_WORKSPACE}/local/docs/m3u/countries/cn.m3u

          iptv-checker -o ${GITHUB_WORKSPACE}/local/output -p 100 -t 60000 ${GITHUB_WORKSPACE}/local/work/countries/kr.m3u
          cp -pr ${GITHUB_WORKSPACE}/local/output/online.m3u ${GITHUB_WORKSPACE}/local/docs/m3u/countries/kr.m3u
          
          iptv-checker -o ${GITHUB_WORKSPACE}/local/output -p 100 -t 60000 ${GITHUB_WORKSPACE}/local/work/countries/tw.m3u
          cp -pr ${GITHUB_WORKSPACE}/local/output/online.m3u ${GITHUB_WORKSPACE}/local/docs/m3u/countries/tw.m3u
          
          iptv-checker -o ${GITHUB_WORKSPACE}/local/output -p 100 -t 60000 ${GITHUB_WORKSPACE}/local/work/countries/hk.m3u
          cp -pr ${GITHUB_WORKSPACE}/local/output/online.m3u ${GITHUB_WORKSPACE}/local/docs/m3u/countries/hk.m3u


          if [ ! -d ${GITHUB_WORKSPACE}/local/docs/m3u/languages ]; then
            mkdir -p ${GITHUB_WORKSPACE}/local/docs/m3u/languages
          fi
          iptv-checker -o ${GITHUB_WORKSPACE}/local/output -p 100 -t 60000 ${GITHUB_WORKSPACE}/local/work/languages/jpn.m3u
          cp -pr ${GITHUB_WORKSPACE}/local/output/online.m3u ${GITHUB_WORKSPACE}/local/docs/m3u/languages/jpn.m3u

          iptv-checker -o ${GITHUB_WORKSPACE}/local/output -p 100 -t 60000 ${GITHUB_WORKSPACE}/local/work/languages/zho.m3u
          cp -pr ${GITHUB_WORKSPACE}/local/output/online.m3u ${GITHUB_WORKSPACE}/local/docs/m3u/languages/zho.m3u

          iptv-checker -o ${GITHUB_WORKSPACE}/local/output -p 100 -t 60000 ${GITHUB_WORKSPACE}/local/work/languages/kor.m3u
          cp -pr ${GITHUB_WORKSPACE}/local/output/online.m3u ${GITHUB_WORKSPACE}/local/docs/m3u/languages/kor.m3u
          
          
          tree -a ${GITHUB_WORKSPACE}/local/docs

#          dirwork=""
#          function read_dir(){
#            for file in `ls $1`
#            do
#              if [ -d $1"/"$file ]; then
#                echo "―folder: "$file
#                if [ ! -d ${GITHUB_WORKSPACE}/local/docs/m3u/$file ]; then
#                  mkdir -p ${GITHUB_WORKSPACE}/local/docs/m3u/$file
#                fi
#                dirwork=$file"/"
#                read_dir $1"/"$file
#              else
#                echo "⊥file: "$file
#                iptv-checker -o ${GITHUB_WORKSPACE}/local/output -p 100 -t 60000 $1"/"$file
#                cp -pr ${GITHUB_WORKSPACE}/local/output/online.m3u ${GITHUB_WORKSPACE}/local/docs/m3u/$dirwork$file
#              fi
#            done
#          }
#          read_dir ${GITHUB_WORKSPACE}/local/work
#          tree -a ${GITHUB_WORKSPACE}/local/docs

      - name: Commit & Push changes 🔥
        uses: Andro999b/push@v1.3
        with:
          branch: main
          directory: ${{ github.workspace }}/local/
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: '🚀 auto publish by bot'
